name: Test Report

on:
  workflow_dispatch:

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        name: Workflow Report
        path: '*.xml'
        reporter: jest-junit
        show-html-notice: true
